name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into VPS and run commands
        uses: appleboy/ssh-action@master
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEYPAIR }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H -v 178.128.119.123 >> ~/.ssh/known_hosts

