name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-test-server:
    name: deploy backend
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /var/www/beesquad && sh deploy.sh
          host: ${{ secrets.HOST}}
          username: root
          port: ${{ secrets.PORT}}
          password: ${{ secrets.PASSWORD}}
          command: cd /var/www/beesquad && sh deploy.sh
