name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into VPS and run commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEYPAIR }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/beesquad && sh deploy.sh
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
